### ISSUE TITLE
Work with pilot implementation sites - Phase 3

### ISSUE THREAD

**Issue by LisaOKeefe1** [data2health/InvenioRDM#103]
Begin work with 1+ pilot implementation sites; this deliverable and subsequent work toward it will depend on local timelines at pilot sites (engagement to identify pilots has begun.

We will begin an implementation project with the first identified site in early January. Other sites are pending confirmation; we will continue to work with NCATS to help identify implementation partners.

**Comment by kristiholmes** [comment]
update details

**Comment by LisaOKeefe1** [comment]
Please refer to https://github.com/inveniosoftware/invenio-app-rdm/issues for project repository, open issues.
