### ISSUE TITLE
Update README.md to reflect InvenioRDM work

### ISSUE THREAD

**Issue by kristiholmes** [data2health/InvenioRDM#91]
@carsonicator I will take a stab at this and then please feel free to jump in and edit my edits. :)
This will likely be something that will evolve as more details are confirmed.

**Comment by carsonicator** [comment]
I changed all references of 'menRva' to 'InvenioRDM'. Should we include some of the content from the InvenioRDM Project Handbook?

**Comment by LisaOKeefe1** [comment]
Please refer to https://github.com/inveniosoftware/invenio-app-rdm/issues for project repository, open issues.
